data_collection/image_topic: "target_detector/image_raw"
target_detector/image_sub_topic: "/image_publisher_1705528996274478816/image_raw"
data_collection/base_frame: "base_link"
data_collection/tool_frame: "link_6"
data_collection/save_path: "/tmp/test_data"
